
const servers = {
  google:             ['8.8.8.8', '8.8.4.4'],
  'amazon.apse1':     ['172.30.0.2'],
  'amazon.apne1':     ['172.31.0.2'],
  'amazon.euwe1':     ['172.16.0.23'],
  blackhole:          ['10.8.11.8'],
  local:              ['10.8.9.8'],
  openans:            ['10.103.116.210','10.103.116.209']
}

const list = {
  'a.sni.fastly.net':               { forward: 'default' },
  'accounts.google.com':            { forward: 'default' },
  'akamaiedge.net':                 { forward: 'default' },
  'amazonaws.com':                  { forward: 'default' },
  'api.ipify.org':                  { forward: 'default' },
  'api.ipify.org.herokudns.com':    { forward: 'default' },
  'au.pool.ntp.org':                { forward: 'default' },
  'auth.docker.io':                 { forward: 'default' },
  'cdn-fastly.deb.debian.org':      { forward: 'default' },
  'cdn.sstatic.net':                { forward: 'default' },
  'checkpoint-api.hashicorp.com':   { forward: 'blackhole', allow: false  },
  'code.jquery.com':                { forward: 'default' },
  'code.jquery.netdna-cdn.com':     { forward: 'default' },
  'deb.debian.org':                 { forward: 'default' },
  'dl-cdn.alpinelinux.org':         { forward: 'default' },
  'dseasb33srnrn.cloudfront.net':   { forward: 'default' },
  'edgekey.net':                    { forward: 'default' },
  'elb-default.us-east-1.aws.dckr.io': { forward: 'default' },
  'elb-hub.us-east-1.aws.dckr.io':  { forward: 'default' },
  'elb-io.us-east-1.aws.dckr.io':   { forward: 'default' },
  'github.com':                     { forward: 'default' },
  'github.map.fastly.net':          { forward: 'default' },
  'global.prod.fastly.net':         { forward: 'default' },
  'googlemail.l.google.com':        { forward: 'default' },
  'hub.docker.com':                 { forward: 'default' },
  'index.docker.io':                { forward: 'default' },
  'iojs.org':                       { forward: 'default' },
  'localunixsocket':                { forward: 'default' },
  'localunixsocket.lan':            { forward: 'default' },
  'mail.google.com':                { forward: 'default' },
  'netflix.com':                    { forward: 'default' },
  'nflxext.com':                    { forward: 'default' },
  'nflximg.net':                    { forward: 'default' },
  'nflxvideo.net':                  { forward: 'default' },
  'nodejs.org':                     { forward: 'default' },
  'openans.co.uk':                  { forward: 'openans' },
  'panther.io':                     { forward: 'local' },
  'panther.local':                  { forward: 'local' },
  'pjp.dgplug.org':                 { forward: 'default' },
  'play.google.com':                { forward: 'blackhole', allow: false },
  'prod.debian.map.fastly.net':     { forward: 'default' },
  'prod.python.map.fastly.net':     { forward: 'default' },
  'pypi.python.org':                { forward: 'default' },
  'registry-1.docker.io':           { forward: 'default' },
  'registry.hub.docker.com':        { forward: 'default' },
  'registry.npmjs.org':             { forward: 'default' },
  'registry.yarnpkg.com':           { forward: 'default' },
  'security.debian.org':            { forward: 'default' },
  'ssl.gstatic.com':                { forward: 'default' },
  'stackauth.com':                  { forward: 'default' },
  'stackoverflow.com':              { forward: 'default' },
  'static.debian.org':              { forward: 'default' },
  'unix.stackexchange.com':         { forward: 'default' },
  'yarnpkg.com':                    { forward: 'default' }
}
